name: Surfactorystudio
favicon: null
layout_spectrum: 0.08824772853404284
typography_spectrum: 0.6218998585827649
title: Surfactory Design Studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#bc8f00'
    - '#8b4700'
    - '#85ffff'
  brandStrength: 0
  lightness: 0.817927758442238
  saturation: 0.009528657654300332
  rhythmicContrast: 0.21415445511229336
purpose: []
