name: Surfactorystudio
favicon: null
layout_spectrum: 0.49371
typography_spectrum: 0
title: Surfactory Design Studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#bc8f00'
    - '#8b4700'
    - '#85ffff'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
